server:
  port: 9000
spring:
  kafka:
    topic:
      avro: users-demo
    consumer:
      schema:
        registry:
          url: localhost:8081
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

swagger:
  exposedPackage: com.demo.controllers
  title: Kafka Demo
  description: Rest API for the Kafka Demo
  contact:
    name: Solstice, LLC
    url: https://sites.google.com/solstice.com/solstice/home
    email: demo@solstice.com

#logging:
#  level:
#    root: DEBUG
#    org.springframework.web: INFO

